"""
Automatic PID auto-tuner for the Mini Pupper Stanford walk.

Instead of you hand-guessing kp/kd, this drives the robot through many short
walks, scores how well each servo tracked the gait, and hunts for the best
gains. It does a COARSE grid first, then several shrinking ZOOM rounds around
the winner (repeating + averaging each candidate to beat run-to-run noise),
then re-runs and plots the best combo.

How it works
------------
Each trial: set candidate kp/kd on the servos, run the firmware `swalk`
command (a few seconds of Stanford trot), capture the per-servo CSV, and score
the tracking. Because the gait setpoint is generated by IK (independent of the
gains) and each servo mostly tracks its own setpoint, the servos are tuned
in parallel: every walk evaluates a different candidate on EACH servo at once,
so N walks cover N candidates per servo (not N*N).

Accuracy comes from two knobs:
- --repeats : run each candidate several times and AVERAGE, so sensor/gait
              noise doesn't crown a lucky combo.
- --rounds  : after the coarse grid, repeatedly zoom a shrinking window around
              the current best, so the final gains aren't stuck on the coarse
              grid points. Stops early once the best stops moving.
Total walks are capped by --max-trials (your accuracy budget).

Score (lower = better), per servo:
    score = RMSE + wpeak*peak_error + wrough*jitter + wrange*reach_shortfall
- RMSE          : overall tracking error over the walk (deg)
- peak_error    : worst instantaneous error, i.e. the swing-phase spike (deg)
- jitter        : RMS of the error's tick-to-tick change (deg) - a proxy for
                  buzzing/instability.
- reach_shortfall: degrees of commanded motion the servo FAILED to achieve
                  (commanded peak-to-peak minus actual peak-to-peak). This is
                  the important one: a too-weak servo (tiny kp) lags smoothly
                  with a SMALLER range of motion, which sneaks past RMSE/peak
                  but never reaches the target angle. The reach term makes the
                  tuner reject those degenerate "it barely moves" gains.

>>> SAFETY <<<
The robot WALKS FORWARD on every trial. Over a 100-walk run that's tens of
metres of travel. Put it on a stand / elevated so the feet don't get traction,
or hold it, or use a low --vx. Keep a hand near the power switch.

Setup (once):
    pip install pyserial matplotlib

Usage:
    python autotune_walk.py --port COM7
    python autotune_walk.py --port COM7 --ids 2,3 --secs 4 --vx 80
    python autotune_walk.py --port COM7 --max-trials 100 --repeats 3   # thorough
    python autotune_walk.py --port COM7 --coarse-only                  # quick

Ctrl-C at any time stops and reports the best combo found so far.

Writes autotune_results.csv (every trial) and, for the winning combo, walk.log
+ walk_servo<ids>.png (via plot_walk.py).
"""

import argparse
import csv
import os
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import plot_walk as pw          # parsing + metrics (reused)
import tune_walk as tw          # serial helpers (reused)

try:
    import serial
except ImportError:
    sys.exit("pyserial not installed. Run:  pip install pyserial")


# ----------------------------- search helpers -----------------------------

def mean(xs):
    xs = list(xs)
    return sum(xs) / len(xs) if xs else 0.0


def parse_grid(text):
    vals = []
    for chunk in text.replace(",", " ").split():
        vals.append(float(chunk))
    if not vals:
        sys.exit(f"empty grid: {text!r}")
    return sorted(set(vals))


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def grid_step(vals):
    """Representative spacing of a sorted grid (for the refine window)."""
    if len(vals) < 2:
        return max(1.0, abs(vals[0]) * 0.25)
    return (max(vals) - min(vals)) / (len(vals) - 1)


def axis_points(center, half, n, lo, hi, round_to):
    """n points spanning [center-half, center+half], clamped, de-duped and
    snapped to a `round_to` grid. Used for the shrinking zoom windows."""
    if n <= 1:
        return [clamp(round(center / round_to) * round_to, lo, hi)]
    pts = set()
    for k in range(n):
        v = center - half + 2.0 * half * k / (n - 1)
        v = clamp(round(v / round_to) * round_to, lo, hi)
        pts.add(v)
    return sorted(pts)


def combos(kps, kds):
    return [(kp, kd) for kp in kps for kd in kds]


def make_assignments(cands):
    """cands: {sid: [combo, ...]} -> list of {sid: combo} covering every
    candidate on every servo, cycling shorter lists so one walk evaluates one
    fresh candidate per servo."""
    n = max(len(v) for v in cands.values())
    out = []
    for i in range(n):
        out.append({sid: cands[sid][i % len(cands[sid])] for sid in cands})
    return out


def servo_metrics(header, rows, sid):
    """RMSE / peak / mean current (from plot_walk) plus jitter and reach."""
    s = pw.servo_series(header, rows, sid)
    m = pw.metrics(s)                       # rmse, peak, mean_cur
    err = [e for e in s["err"] if e is not None]
    if len(err) < 2:
        err = [sp - nw for sp, nw in zip(s["set"], s["now"])
               if sp is not None and nw is not None]
    diffs = [err[i] - err[i - 1] for i in range(1, len(err))]
    m["rough"] = (sum(d * d for d in diffs) / len(diffs)) ** 0.5 if diffs else 0.0
    m["n_samples"] = len(err)

    # reach: did the actual angle cover the commanded range of motion?
    setv = [v for v in s["set"] if v is not None]
    nowv = [v for v in s["now"] if v is not None]
    pp_set = (max(setv) - min(setv)) if setv else 0.0
    pp_now = (max(nowv) - min(nowv)) if nowv else 0.0
    m["pp_set"] = pp_set
    m["pp_now"] = pp_now
    m["reach"] = (pp_now / pp_set) if pp_set > 1e-6 else 0.0
    m["shortfall"] = max(0.0, pp_set - pp_now)   # deg of motion NOT achieved
    return m


def score_of(m, wpeak, wrough, wrange):
    return (m["rmse"] + wpeak * m["peak"] + wrough * m["rough"]
            + wrange * m.get("shortfall", 0.0))


def aggregate(results, wpeak, wrough, wrange):
    """results: {sid: {combo: [metrics,...]}} -> {sid: {combo: summary}}."""
    out = {}
    for sid, by_combo in results.items():
        out[sid] = {}
        for combo, ms in by_combo.items():
            summ = {
                "rmse": mean(m["rmse"] for m in ms),
                "peak": mean(m["peak"] for m in ms),
                "rough": mean(m["rough"] for m in ms),
                "mean_cur": mean(m["mean_cur"] for m in ms),
                "reach": mean(m["reach"] for m in ms),
                "shortfall": mean(m["shortfall"] for m in ms),
                "n": len(ms),
            }
            summ["score"] = score_of(summ, wpeak, wrough, wrange)
            out[sid][combo] = summ
    return out


def best_combo(agged_for_sid):
    return min(agged_for_sid.items(), key=lambda kv: kv[1]["score"])


# ----------------------------- serial trial -------------------------------

def set_gains(ser, sid, kp, kd, wait=0.15):
    tw.send(ser, f"{sid} set kp_position {kp:g}", wait)
    tw.send(ser, f"{sid} set kd_position {kd:g}", wait)


def capture_walk(ser, ids, secs, hz, vx, timeout):
    cmd = f"swalk {secs} {hz} {vx:g} " + " ".join(str(i) for i in ids)
    ser.reset_input_buffer()
    tw.send(ser, cmd, 0.0)
    lines, started, t0 = [], False, time.time()
    while time.time() - t0 < timeout:
        raw = ser.readline().decode(errors="replace").rstrip("\r\n")
        if not raw:
            continue
        if "#WALK_BEGIN" in raw:
            started = True
        if started:
            lines.append(pw.clean(raw))
        if "#WALK_END" in raw:
            break
    return lines


def run_trial(ser, assignment, args):
    """Apply the per-servo gains, walk once, return {sid: metrics}."""
    for sid, (kp, kd) in assignment.items():
        set_gains(ser, sid, kp, kd)
    lines = capture_walk(ser, args.ids, args.secs, args.hz, args.vx,
                         args.secs + 8)
    _, header, rows = pw.extract_last_block(lines)
    if header is None or not rows:
        return None
    return {sid: servo_metrics(header, rows, sid) for sid in args.ids}


# ------------------------------- driver -----------------------------------

def do_search(assignments, evalfn, results, wpeak, wrough, wrange, log_rows,
              label=""):
    """Run each assignment through evalfn, folding metrics into `results`.
    evalfn(assignment) -> {sid: metrics} or None (skipped)."""
    total = len(assignments)
    for i, asg in enumerate(assignments, 1):
        desc = "  ".join(f"s{sid}:kp{kp:g}/kd{kd:g}"
                         for sid, (kp, kd) in asg.items())
        print(f"[{label}{i}/{total}] {desc}", flush=True)
        m = evalfn(asg)
        if m is None:
            print("    (no data captured - skipped)")
            continue
        for sid, met in m.items():
            combo = asg[sid]
            results.setdefault(sid, {}).setdefault(combo, []).append(met)
            sc = score_of(met, wpeak, wrough, wrange)
            print(f"    servo {sid}: RMSE {met['rmse']:.2f}  peak {met['peak']:.2f}"
                  f"  jitter {met['rough']:.2f}  reach {met['reach']*100:.0f}%"
                  f"  -> score {sc:.2f}")
            log_rows.append({
                "phase": label.strip() or "coarse", "servo": sid,
                "kp": combo[0], "kd": combo[1], "rmse": round(met["rmse"], 3),
                "peak": round(met["peak"], 3), "jitter": round(met["rough"], 3),
                "reach_pct": round(met["reach"] * 100, 1),
                "mean_cur": round(met["mean_cur"], 1),
                "score": round(sc, 3),
            })


def print_ranking(agged, wpeak, wrough, wrange):
    for sid in sorted(agged):
        print(f"\n=== Servo {sid} - top candidates (score = RMSE + "
              f"{wpeak:g}*peak + {wrough:g}*jitter + {wrange:g}*reach_shortfall) ===")
        rows = sorted(agged[sid].items(), key=lambda kv: kv[1]["score"])
        print(f"  {'kp':>6} {'kd':>7} {'RMSE':>7} {'peak':>7} {'jitter':>7} "
              f"{'reach':>6} {'score':>7} {'n':>3}")
        for combo, s in rows[:8]:
            print(f"  {combo[0]:>6g} {combo[1]:>7g} {s['rmse']:>7.2f} "
                  f"{s['peak']:>7.2f} {s['rough']:>7.2f} {s['reach']*100:>5.0f}% "
                  f"{s['score']:>7.2f} {s['n']:>3}")


def main():
    ap = argparse.ArgumentParser(description="Auto-tune walk PID (kp/kd)")
    ap.add_argument("--port", help="serial port, e.g. COM7 (lists ports if omitted)")
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--ids", default="2,3", help="servo ids to tune (default 2,3)")
    ap.add_argument("--secs", type=int, default=4, help="walk length per trial")
    ap.add_argument("--hz", type=int, default=50, help="log sample rate")
    ap.add_argument("--vx", type=float, default=100.0, help="walk speed mm/s")
    ap.add_argument("--kp-grid", default="60,90,120,150,180",
                    help="coarse kp candidates")
    ap.add_argument("--kd-grid", default="800,1200,1600,2000",
                    help="coarse kd candidates")
    ap.add_argument("--wpeak", type=float, default=0.10,
                    help="weight on peak error in the score")
    ap.add_argument("--wrough", type=float, default=0.30,
                    help="weight on jitter/instability in the score")
    ap.add_argument("--wrange", type=float, default=1.0,
                    help="weight on reach shortfall (deg of motion not achieved)."
                         " Higher = reject gains that don't reach the angle.")
    ap.add_argument("--coarse-only", action="store_true",
                    help="skip the refine passes")
    ap.add_argument("--max-trials", type=int, default=80,
                    help="hard cap on number of walks (accuracy budget)")
    ap.add_argument("--repeats", type=int, default=2,
                    help="times to repeat each candidate and average "
                         "(more = less noise, more walks)")
    ap.add_argument("--rounds", type=int, default=4,
                    help="max zoom/refine rounds after the coarse pass")
    ap.add_argument("--refine-n", type=int, default=3,
                    help="grid points per axis in each refine round")
    ap.add_argument("--shrink", type=float, default=0.55,
                    help="window shrink factor per refine round (0-1)")
    ap.add_argument("--settle", type=float, default=1.0,
                    help="pause between trials, seconds (let servos rest)")
    ap.add_argument("--kp-bounds", default="40,400",
                    help="kp search bounds; zoom can't go below/above these")
    ap.add_argument("--kd-bounds", default="100,4000")
    args = ap.parse_args()

    args.ids = tw.parse_ids(args.ids)
    kp_grid = parse_grid(args.kp_grid)
    kd_grid = parse_grid(args.kd_grid)
    kp_lo, kp_hi = parse_grid(args.kp_bounds)[0], parse_grid(args.kp_bounds)[-1]
    kd_lo, kd_hi = parse_grid(args.kd_bounds)[0], parse_grid(args.kd_bounds)[-1]

    port = tw.pick_port(args.port)
    print(f"Opening {port} @ {args.baud} ...")
    try:
        ser = serial.Serial(port, args.baud, timeout=0.2)
    except serial.SerialException as e:
        sys.exit(f"Could not open {port}: {e}\nIs idf.py monitor still open?")

    n_coarse = len(kp_grid) * len(kd_grid)
    planned = min(args.max_trials,
                  n_coarse + (0 if args.coarse_only else
                              args.rounds * args.refine_n ** 2 * args.repeats))
    est = planned * (args.secs + 2 + args.settle)
    print(f"\n*** The robot will WALK FORWARD up to {planned} times "
          f"(~{planned * args.secs * args.vx / 1000:.0f} m of travel). "
          f"Put it on a stand so it can't drive off. ***")
    print(f"    budget: {args.max_trials} walks | coarse {n_coarse}, then up to "
          f"{args.rounds} zoom rounds x {args.refine_n}x{args.refine_n} x{args.repeats} reps")
    print(f"    est. total time: ~{est/60:.1f} min\n")

    time.sleep(0.5)
    ser.reset_input_buffer()
    tw.send(ser, "cli on", 0.4)

    results = {}
    log_rows = []
    state = {"used": 0}

    def evalfn(asg):
        m = run_trial(ser, asg, args)
        time.sleep(args.settle)
        return m

    def run_batch(cands, repeats, label):
        """Run every candidate `repeats` times (averaged later), honouring the
        --max-trials budget. Returns True if budget remains."""
        asgs = make_assignments(cands) * repeats
        remaining = args.max_trials - state["used"]
        if remaining <= 0:
            print("  budget exhausted - stopping.")
            return False
        asgs = asgs[:remaining]
        do_search(asgs, evalfn, results, args.wpeak, args.wrough, args.wrange,
                  log_rows, label=label)
        state["used"] += len(asgs)
        print(f"  -- walks used: {state['used']}/{args.max_trials} --")
        return state["used"] < args.max_trials

    try:
        # ---- coarse pass: same grid on every servo (1 rep) ----
        cands = {sid: combos(kp_grid, kd_grid) for sid in args.ids}
        keep_going = run_batch(cands, 1, "coarse ")
        agged = aggregate(results, args.wpeak, args.wrough, args.wrange)

        # ---- zoom rounds: shrinking window around each servo's best ----
        if not args.coarse_only:
            kp_half, kd_half = grid_step(kp_grid), grid_step(kd_grid)
            prev_best = None
            for r in range(args.rounds):
                if not keep_going:
                    break
                rcands = {}
                for sid in args.ids:
                    (bkp, bkd), _ = best_combo(agged[sid])
                    rkps = axis_points(bkp, kp_half, args.refine_n, kp_lo, kp_hi, 1)
                    rkds = axis_points(bkd, kd_half, args.refine_n, kd_lo, kd_hi, 25)
                    rcands[sid] = combos(rkps, rkds)
                    print(f"\nRound {r+1}: servo {sid} around kp={bkp:g}/kd={bkd:g} "
                          f"-> kp{rkps} kd{rkds}")
                keep_going = run_batch(rcands, args.repeats, f"round{r+1} ")
                agged = aggregate(results, args.wpeak, args.wrough, args.wrange)

                cur_best = {sid: best_combo(agged[sid])[0] for sid in args.ids}
                if cur_best == prev_best:
                    print("\nConverged - best unchanged this round; stopping.")
                    break
                prev_best = cur_best
                kp_half *= args.shrink
                kd_half *= args.shrink

    except KeyboardInterrupt:
        print("\nInterrupted - reporting best so far.")
        agged = aggregate(results, args.wpeak, args.wrough, args.wrange)

    if not agged:
        tw.send(ser, "cli off", 0.2)
        ser.close()
        sys.exit("No results captured. Is the 'swalk' firmware flashed?")

    print_ranking(agged, args.wpeak, args.wrough, args.wrange)

    # winning combo per servo
    best = {}
    for sid in args.ids:
        combo, summ = best_combo(agged[sid])
        best[sid] = (combo, summ)

    print("\n================ BEST GAINS ================")
    set_parts = []
    for sid in args.ids:
        (kp, kd), s = best[sid]
        print(f"  servo {sid}: kp={kp:g} kd={kd:g}   "
              f"(RMSE {s['rmse']:.2f}, peak {s['peak']:.2f}, jitter {s['rough']:.2f}, "
              f"reach {s['reach']*100:.0f}%, avg of {s['n']})")
        set_parts.append(f"--set {sid}:kp={kp:g},kd={kd:g}")
    cmd = ("python tools\\tune_walk.py --port " + port +
           " --ids " + ",".join(str(i) for i in args.ids) + " " +
           " ".join(set_parts))
    print("\nReproduce / verify with:\n  " + cmd)

    # save the full trial log
    csv_path = "autotune_results.csv"
    with open(csv_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["phase", "servo", "kp", "kd", "rmse",
                                          "peak", "jitter", "reach_pct",
                                          "mean_cur", "score"])
        w.writeheader()
        w.writerows(log_rows)
    print(f"\nsaved every trial -> {os.path.abspath(csv_path)}")

    # final: apply the best gains, walk once more, and plot it
    print("\nRunning a final walk with the best gains for the plot ...")
    for sid in args.ids:
        (kp, kd), _ = best[sid]
        set_gains(ser, sid, kp, kd)
    lines = capture_walk(ser, args.ids, max(args.secs, 6), args.hz, args.vx,
                         max(args.secs, 6) + 8)
    tw.send(ser, "cli off", 0.2)
    ser.close()

    if any("#WALK_BEGIN" in l for l in lines):
        with open("walk.log", "w", newline="\n") as f:
            f.write("\n".join(lines) + "\n")
        plotter = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "plot_walk.py")
        subprocess.run([sys.executable, plotter, "walk.log"], check=False)
    else:
        print("(final walk capture failed - gains are still set on the robot)")


if __name__ == "__main__":
    main()
